import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | voter',
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 lg:px-8 py-10 lg:py-14">
      <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">
        Last updated: 2026-05-09
      </p>
      <h1 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-6">
        Terms of Service
      </h1>

      <div className="space-y-6 text-base text-gray-800 leading-relaxed">
        <Section title="What this is">
          <p>
            voter is a non-partisan tool to help voters compare candidates in
            US federal midterm primary elections. We aggregate publicly
            available data (campaign websites, Ballotpedia, FEC filings,
            congressional voting records) and let you browse it through
            scorecards plus an LLM-powered match tool.
          </p>
        </Section>

        <Section title="Match score disclaimer">
          <p>
            Match scores reflect &ldquo;closest alignment&rdquo; based on
            available public data. We never claim a candidate is &ldquo;best&rdquo;
            for you. Stances change. Voting records are partial. Our data may be
            incomplete or stale. <strong>Do your own research before voting.</strong>
          </p>
          <p>
            If you find an inaccurate stance summary or missing track-record,
            please report it via the GitHub issue tracker. We correct errors
            and surface corrections in the candidate&apos;s detail page.
          </p>
        </Section>

        <Section title="Track-record annotations">
          <p>
            We surface inconsistencies between a candidate&apos;s stated
            platform and their voting record or donor profile. These notes are
            generated by an LLM from the underlying public data and reviewed
            by a human before activation. Every note cites a specific bill or
            statement so you can verify it yourself. We do not editorialize.
          </p>
        </Section>

        <Section title="Acceptable use">
          <ul className="list-disc pl-5 space-y-1">
            <li>Don&apos;t use this tool to harass candidates or voters.</li>
            <li>Don&apos;t scrape the site to build derivative voter-targeting databases.</li>
            <li>Don&apos;t spam our APIs (we rate-limit and will block abusers).</li>
          </ul>
        </Section>

        <Section title="Liability">
          <p>
            voter is provided &ldquo;as is&rdquo; without warranty of any kind.
            We are not liable for voting decisions made based on information
            from this site. This is a research aid, not legal or political
            advice.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We may update these terms. Material changes will be announced on
            the homepage for at least 30 days before taking effect.
          </p>
        </Section>
      </div>

      <div className="mt-10 pt-6 border-t border-gray-200 flex gap-4 text-sm">
        <Link href="/privacy" className="text-blue-600 underline">Privacy policy</Link>
        <Link href="/data-rights" className="text-blue-600 underline">Manage your data</Link>
        <Link href="/" className="text-blue-600 underline">Home</Link>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold text-gray-900 mb-2">{title}</h2>
      <div className="space-y-2">{children}</div>
    </section>
  );
}
